language: php

dist: trusty
sudo: false

notifications:
    email:
        on_success: never
        on_failure: change

cache:
    directories:
        - $HOME/.composer/cache

services:
    - mysql

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm
    - nightly

env:
    - WP_VERSION=latest WP_MULTISITE=0

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: WP_VERSION=latest WP_MULTISITE=1
        - php: 7.0
          env: WP_VERSION=latest WP_MULTISITE=1
        - php: 7.1
          env: WP_VERSION=latest WP_MULTISITE=1
        - php: nightly
          env: WP_VERSION=latest WP_MULTISITE=1
    allow_failures:
        - php: nightly

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
    # - phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
    - phpunit
